apiVersion: v1
kind: Secret 
metadata:
    name: mysql-secret
type: Opaque
data: 
    mysql-root-username: bW9oYW1lZA==
    mysql-root-password: bW9oYW1lZDEyMw==
    phpmyadmin-controluser: dXNlcg==
    phpmyadmin-controlpass: cGFzc3dvcmQ=
