apiVersion: apps/v1
kind: Deployment
metadata:
    name: prestashop
    labels:
        app: prestashop
spec:
    replicas: 1
    selector:
        matchLabels:
            app: prestashop
    template:
        metadata:
            labels:
                app: prestashop
        spec:
            containers: 
            - name: prestashopcontainer
              image: ayadinou/prestashopdclick:02
              ports:
              - containerPort: 80  
              env:
                #              - name: PMA_CONTROLUSER
                #                valueFrom:
                #                    secretKeyRef:
                #                        name: mysql-secret
                #                        key: phpmyadmin-controluser 
                #              - name: PMA_CONTROLPASS
                #                valueFrom:
                #                    secretKeyRef:
                #                        name: mysql-secret
                #                        key: phpmyadmin-controlpass
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: mysql-root-username
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: mysql-root-password

              - name: MYSQL_HOST
                valueFrom:
                  configMapKeyRef:
                    name: mysql-configmap
                    key: database_url
---
apiVersion: v1
kind: Service
metadata:
    name: prestashop-service
spec:
    selector:
        app: prestashop
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 80
          nodePort: 30000
