apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-www-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Mi
